### ISSUE TITLE
ObjectDisposedException

### ISSUE THREAD

**Issue by dlbroadfoot** [launchdarkly/dotnet-eventsource#49]
HI,

Our .NET client application has started throwing the following error all of a sudden (in the last few days).

System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'SslStream'.
   at System.Net.ConnectStream.EndRead(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.<ReadAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.IO.StreamReader.<ReadBufferAsync>d__97.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.IO.StreamReader.<ReadLineAsyncInternal>d__60.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LaunchDarkly.EventSource.EventSourceStreamReader.<ReadLineAsync>d__2.MoveNext()

**Comment by eli-darkly** [comment]
Thanks for letting us know. Can you tell me what version of the package you're using, and whether you're using any non-default properties in the Configuration class? Also, what happens after you see this exception— does it continue normally, or reconnect the stream, or stop working?

**Comment by dlbroadfoot** [comment]
Hi Eli,

We're using 3.1.1.0 of the package. As our application is client side and deployed to on users' machines we are unable to easily update the SDK. It seems to have stopped working for all our clients last week which seems to indicate it's a change on your server side?

The error is thrown about every 5 minutes.  Once the error occurs our clients no longer get real time notifications when a feature toggle is changed.

Our configuration is: 

`var config = new Configuration(new Uri(url), delayRetryDuration: TimeSpan.FromSeconds(5));`

**Comment by dlbroadfoot** [comment]
FYI I sent through some additional information in a support ticket (as it contained api keys)

**Comment by eli-darkly** [comment]
@dlbroadfoot OK, it's probably best to continue through the support team at this point, especially if this might be an issue with the service rather than something specific to the .NET SDK code. I'm on the SDK development team and they will communicate with me as they investigate. I'll leave this issue open for now just in case someone else has a similar problem and wants to chime in.
